name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest

    # https://stackoverflow.com/a/76209121/7304977
    # strategy:
    #   matrix:
    #     node-version: [16.14.2]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.x'
      
      - name: Clean install
        run: npm ci

      - name: Install firebase-tools
        run: npm install -g firebase-tools
      
      - name: Install execa for Actions script
        run: npm install execa
      
      - name: Create preview channel
        id: create_preview
        uses: actions/github-script@v4
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        with:
          script: |
            import {execa} from 'execa'
            // const execa = require('execa')

            const pr_number = context.issue.number

            const command = `firebase hosting:channel:create ${pr_number}`
            const { stdout } = await execa(command)
            
            // stdout will look something like this:
            //
            // ```
            // $ firebase hosting:channel:create 123456
            // 
            // +  hosting:channel: Channel 123456 has been created on site <site>.
            // +  hosting:channel: Channel 123456 will expire at <timestamp>.
            // +  hosting:channel: Channel URL: https://<project-id>--123456-<random-hash>.web.app
            // 
            // To deploy to this channel, use firebase hosting:channel:deploy 123456.
            // ```
            console.log('stdout', stdout)

            // We need to extract the channel URL
            const preview_url = stdout.split('\n').find(line => line.includes('Channel URL:')).split(' ').pop().trim()

            // Now return it as an output
            return {
              preview_url
            }

      - name: Deploy to preview channel
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase hosting:channel:deploy ${{ steps.create_preview.outputs.preview_url }}
      
      - name: Comment on PR with preview URL
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview site: ${steps.create_preview.outputs.preview_url}`
            })